version: '3'
services:
  hello-world-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 158543191340.dkr.ecr.ap-southeast-1.amazonaws.com/node
    container_name: hello-world-container
    networks:
      - hello-world-network

  hello-world-nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: 158543191340.dkr.ecr.ap-southeast-1.amazonaws.com/nodenginx
    container_name: nginx-container
    networks:
      - hello-world-network
    ports:
      - "80:80"

networks:
  hello-world-network:
    driver: bridge

